"""empty message

Revision ID: 23c3a8c2cc2b
Revises: 
Create Date: 2022-10-03 23:39:45.761052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23c3a8c2cc2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('language', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('user_name', sa.String(length=70), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('permission', sa.Enum('USER', 'AVERAGE_USER', 'HIGH_USER', 'ADMIN', name='Permission'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('topic_names',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('topic_name', sa.String(length=70), nullable=True),
    sa.Column('description', sa.String(length=70), nullable=True),
    sa.Column('language', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['language'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('topic_name')
    )
    op.create_table('notes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=True),
    sa.Column('tutorial', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('permission', sa.Enum('USER', 'AVERAGE_USER', 'HIGH_USER', 'ADMIN', name='Permission'), nullable=True),
    sa.Column('topic_names', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_names'], ['topic_names.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('topic_names')
    op.drop_table('user')
    op.drop_table('languages')
    # ### end Alembic commands ###
